version: 1

merge:
  whitelist:
    labels: ["accepted", "bulldozer"]
  blacklist:
    labels: ["work in progress"]
  # "required_status" is a list of additional status contexts that must pass
  # before bulldozer can merge a pull request. This is useful if you want to
  # require extra testing for automated merges, but not for manual merges.
  # code checks for state of the given status to be equal to 'success'
  required_statuses:
    - "percy/verso"
    - "ci/jetbridge-jenkins"
    - "continuous-integration/codeship"
  method: merge
  # If true, bulldozer will delete branches after their pull requests merge.
  delete_after_merge: true

# if PR has been labelled accepted, bulldozer will attempt to keep it up to date with master
update:
  whitelist:
    labels: ["accepted", "bulldozer"]
     
  
