pull_request_rules:
  - name: automatic merge on review
    conditions:
      - "#approved-reviews-by>=1"
      - base=master
    actions:
      merge:
        method: merge
        strict: true
        strict_method: rebase
